version: "3.4"

x-base: &base
  logging:
    driver: 'json-file'
    options:
      max-size: '10m'
      max-file: '5'
  # https://docs.docker.com/compose/compose-file/#restart
  restart: unless-stopped
  # when deployed using docker swarm, cf.: https://docs.docker.com/compose/compose-file/#restart_policy

services:
  mautic:
    <<: *base
    image: mautic/mautic:apache
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      MAUTIC_DB_HOST: mysql
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mauticdbpass
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0

  mysql:
    <<: *base
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mauticdbpass

  nginx:
    <<: *base
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - sslcerts:/etc/ssl/private
    depends_on:
      - mautic
    entrypoint:
      - "bash"
      - "-c"
    command: |
      "if [ ! -f /etc/ssl/private/mautic.crt ]; then
        echo 'ssl certificate missing, installing openssl to create a new one'
        apt-get update && apt-get install openssl -y
        openssl req -x509 -newkey rsa:2048 -sha256 -nodes -keyout /etc/ssl/private/mautic.key -out /etc/ssl/private/mautic.crt -subj '/CN=mautic.local' -days 3650
        echo 'Created new ssl certificate'
      fi
      exec nginx -g 'daemon off;'"

volumes:
  mysql:
  sslcerts: